# Generated by Django 6.0.1 on 2026-02-09 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contacto',
        ),
    ]
