# Generated by Django 6.0.1 on 2026-03-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productoDfr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock Disponible')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('foto_binaria', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
